# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: mangfengweb main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm install deps
      run: npm install
    - name: build project
      run: npm run build
    
    - name: scp-deployer
      # You may pin to the exact commit or the version.
      # uses: siva1024/scp-deployer@595af961c23bfad4cc7c1bcdfe9b57fb840e7cb9
      uses: siva1024/scp-deployer@v1.0
      with:
        # ssh remote host
        host: ${{ secrets.REMOTE_HOST }}
        # ssh remote user
        username: ${{ secrets.REMOTE_USER }}
        # ssh remote port
        port: 22
        # content of ssh private key. ex raw content of ~/.ssh/id_rsa
        # key: # optional
        # ssh remote password
        password: ${{ secrets.REMOTE_PASSWORD }}
        # source to copy from
        source: "build/"
        # destination to download on server
        target: ${{ secrets.REMOTE_TARGET }}

